### PR TITLE
Fix "NullPointerException: Profile name must not be null" on paper 1.20.2 server

### PR DESCRIPTION
**Pull request by GregorSomething**
Partial stacktrace of the error:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.stefvanschie.inventoryframework.font.util.Font
        at ee.pelar.pelarcosmetics.gui.HatGUI.navigationPane(HatGUI.java:138) ~[pelarcosmetics-1.0.jar:?]
        at ee.pelar.pelarcosmetics.gui.HatGUI.showHatGUI(HatGUI.java:49) ~[pelarcosmetics-1.0.jar:?]
        at ee.pelar.pelarcosmetics.gui.HatGUI.showHatGUI(HatGUI.java:36) ~[pelarcosmetics-1.0.jar:?]
        at ee.pelar.pelarcosmetics.commands.subcommands.MenuCommand.perform(MenuCommand.java:40) ~[pelarcosmetics-1.0.jar:?]
        at ee.pelar.pelarcosmetics.commands.CommandManager.onCommand(CommandManager.java:31) ~[pelarcosmetics-1.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException: Profile name must not be null [in thread "Server thread"]
        at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
        at com.github.stefvanschie.inventoryframework.util.SkullUtil.setSkull(SkullUtil.java:54) ~[pelarcosmetics-1.0.jar:?]
        at com.github.stefvanschie.inventoryframework.util.SkullUtil.getSkull(SkullUtil.java:41) ~[pelarcosmetics-1.0.jar:?]
        at com.github.stefvanschie.inventoryframework.font.CSVFont.lambda$new$1(CSVFont.java:46) ~[pelarcosmetics-1.0.jar:?]
        at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.github.stefvanschie.inventoryframework.font.CSVFont.<init>(CSVFont.java:46) ~[pelarcosmetics-1.0.jar:?]
        at com.github.stefvanschie.inventoryframework.font.util.Font.<clinit>(Font.java:29) ~[pelarcosmetics-1.0.jar:?]
```

To fix this I set a random name to GameProfile.
(Tested this and it worked)

### CODE REVIEW

**Comment by GregorSomething** [comment]
Compiled it.
[IF-0.10.13-SNAPSHOT.jar.zip](https://github.com/stefvanschie/IF/files/13759134/IF-0.10.13-SNAPSHOT.jar.zip)

**Review by stefvanschie — CHANGES_REQUESTED** [review]
Thank you for your pull request. The change looks good, but Spigot also introduced a consistency check which fails using this.
```
Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
```
This should be avoided by also setting the `serializedProfile` field properly.

As for the name given, this name apparently appears in the name of the item. I.e, for this change the name of the skull becomes "RandomName's Head". In the past this was a generic "Player Head". I believe this can be avoided if the name is set to an empty string. I think we should do that, because it retains the old behaviour and the "Player Head" string is completely translated, meaning that it will have the proper name for whatever language the player is using. This won't be the case if we decide on a name ourselves.

See also pull request #652 which does something similar.

**Comment by Tiri2** [comment]
When will it be mered? I need the change so that I can continue programming

**Comment by stefvanschie** [comment]
Once the requested changes are addressed then it should be good to be merged.

**Comment by GregorSomething** [comment]
I did not quite understand what you ment, but I did something and tested, it does not give warning to console and its name is Player Head if other name was not given.

**Comment by Tiri2** [comment]
yea yea - i need the fix of the exception, so i can continue to code my stuff yk?

**Comment by stefvanschie** [comment]
> I did not quite understand what you ment, but I did something and tested, it does not give warning to console and its name is Player Head if other name was not given.

The name change is good, thank you for that. The warning is relatively new, but I just tested your code and it still appears on Spigot 1.20.4. Maybe you were testing an older version?

The specific code for the warning can be found here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java.
Spigot has introduced a new `serializedProfile` field that needs to be set alongside the regular `profile` field. So for versions where this field exists (not all will have it, so this needs to be checked first), we will have to set this field as well, to avoid this warning.
This can be done with reflection, in a way similar to line 132 in the `CraftMetaSkull` from the above link.

**Comment by GregorSomething** [comment]
Updated that, but I had to use setProfile method to do that, because I did not find other any other way to get serializedProfile.

**Review by stefvanschie — CHANGES_REQUESTED** [review]
Thank you, this all looks good. Using `setProfile` instead of setting the `serializedProfile` field directly is a better idea than what I proposed. If you could add the necessary imports to your pull request (for Method and InvocationTargetException), so the CI passes, then I can merge this.

**Review by stefvanschie — APPROVED** [review]
Everyting looks good now, thank you, merged.

**Comment by thegatesdev** [comment]
Just as a heads up, after [snapshot 24w14a](https://www.minecraft.net/en-us/article/minecraft-snapshot-24w14a) the name field is optional, and will be resolved automatically if it isn't present.
Not entirely sure if people depend on the name field, but when the update comes out it might be useful to leave the field empty once again for newer versions.

**Comment by stefvanschie** [comment]
Thank you for the heads up. I think it's simplest to provide an empty string as the name for all versions. This saves us from having to implement version-specific checks and keeps the behaviour more consistent.

**Pull request merged**
