### PR TITLE
Add fillWith method with a parameter for the action to execute

### PR DESCRIPTION
**Pull request by pavog**
This adds a method to fill a static pane with an itemstacks and add an action to all of them.

### CODE REVIEW

**Comment by pavog** [comment]
Whoops, the whitespaces / tabs are still not correct. Maybe you can fix them? @stefvanschie

**Comment by tth05** [comment]
I don't see how this method is useful, because if you want the same action for every item you can just use Pane#setOnClick

**Comment by pavog** [comment]
You're right. But you still need to check the item / material in the action provided to Pane#setOnClick, since StaticPane#fillWith only fills empty spots and you may only want to execute the action on the item you filled the gui with.

**Comment by tth05** [comment]
Ok that makes more sense, I didn't think about that :+1:

**Comment by stefvanschie** [comment]
Thank you, merged.

**Pull request merged**
