### PR TITLE
Update PatternPain Copy

### PR DESCRIPTION
**Pull request by VyperzDev**
This might fix the rotation error when trying to copy a PatternPain.

I have no clue as I can not seem to figure out how implement my fork into the maven package.

### CODE REVIEW

**Comment by thegatesdev** [comment]
What is the rotation error you are mentioning?
It doesn't look like the changes actually change the outcome.
`flipHorizontally(isFlippedHorizontally())` and `flipVertically(isFlippedVertically())` both get and assign the value directly.
`setRotation` does do some additional checks before assigning, but those should've passed for the original value (`this.rotation`) as well

**Comment by VyperzDev** [comment]
Error: Rotations can only be applied to square panes

It happens when you try and Copy a PatternPain.
I looked into the copy method in StaticPain and just copied it.

**Comment by thegatesdev** [comment]
Ah, right, when the user hasn't set the rotation it still calls `setRotation` when copying, which fails for non-square pattern panes. Should be solved with this then.

**Review by stefvanschie — APPROVED** [review]
Thank you for your PR, merged.

**Pull request merged**
