### PR TITLE
Don't reopen GUIs on update when not necessary to prevent flickering

### PR DESCRIPTION
**Pull request by jdkeke142**
A current problem with IF is that with each GUI update, even when only items are changed, it reopens the inventory which causes some kinds of flickering.

For a static GUI or one that updates rarely this is not a big concern. However, as stated in the issue https://github.com/stefvanschie/IF/issues/205, it becomes a bigger problem in GUIs that need to be updated more frequently.

This PR is intended to correct the problem without changing the external use of the API, now Gui#update will judge itself if it is necessary to reopen the GUI depending on whether it is considered dirty or not.

### CODE REVIEW

**Comment by stefvanschie** [comment]
I've changed the base to version 0.10.7, since I need more time to look at this and want to get an update out to add support for Minecraft 1.19.

**Comment by jdkeke142** [comment]
> Thank you for your PR. I've changed the base to version 0.10.7, since I need more time to look at this and want to get an update out to add support for Minecraft 1.19.

I see. If you want me to change anything let me know

**Review by stefvanschie — CHANGES_REQUESTED** [review]
Sorry for the delay in getting to this. There are some guis that don't behave properly with these changes. In particular:

- The AnvilGui doesn't place items back in the player inventory after updating the gui. An item on the cursor is also only visible after the gui has been updated.
- In the BeaconGui, when you pick up an item from the player inventory, it becomes invisible/disappears.
- For the CartographyTableGui, when you take an item from the top inventory the item is duplicated, but when you take an item form the bottom inventory it disappears.
- In the CraftingTableGui, items in the player inventory aren't visible.
- In the EnchantingTableGui taking an item causes it to become invisible/disappear.
- In the GrindstoneGui when you take an item it is duplicated.
- And for the StonecutterGui you cannot take any items, even if the event for this item is not cancelled.

The other guis seem to be working correctly.

**Comment by stefvanschie** [comment]
This was closed automatically along the deletion of the `0.10.7` branch, apologies for this. Feel free to create another PR for these changes.

**Pull request closed without merging**
